apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "9"
    description: LAN pihole
  creationTimestamp: null
  generation: 1
  labels:
    k8s-app: pihole
    location: lan
  name: pihole
  selfLink: /apis/extensions/v1beta1/namespaces/lan/deployments/pihole
spec:
  progressDeadlineSeconds: 600
  replicas: 5
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s-app: pihole
      location: lan
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        description: LAN pihole
      creationTimestamp: null
      labels:
        k8s-app: pihole
        location: lan
      name: pihole
    spec:
      containers:
      - env:
        - name: TZ
          value: Berlin/Europe
        - name: DNS1
          value: 54.93.169.181
        - name: DNS2
          value: 172.104.135.61
        volumeMounts:
        - mountPath: /etc/pihole
          name: k8s-cfg-pihole-pihole
        - mountPath: /etc/dnsmasq.d
          name: k8s-cfg-pihole-dnsmasq
        image: pihole/pihole
        imagePullPolicy: Always
        name: pihole
        ports:
        - containerPort: 80
          name: pihole-http
          protocol: TCP
        - containerPort: 53
          name: dns
          protocol: TCP
        - containerPort: 53
          name: dns-udp
          protocol: UDP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        securityContext:
          privileged: false
          procMount: Default
      dnsPolicy: ClusterFirst
      hostNetwork: false
      restartPolicy: Always
#      nodeSelector:
#        location: lan
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: k8s-cfg-pihole-pihole
        hostPath:
          path: /root/k8s-cfg/pihole/pihole
          type: Directory
      - name: k8s-cfg-pihole-dnsmasq
        hostPath:
          path: /root/k8s-cfg/pihole/dnsmasq
          type: Directory
status: {}
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/address-pool: lan-loadbalancer
    metallb.universe.tf/allow-shared-ip: lan-loadbalancer
  labels:
    k8s-app: pihole
  name: pihole-tcp-100
  namespace: lan
spec:
  externalTrafficPolicy: Cluster
  loadBalancerIP: 192.168.1.100
  ports:
  - name: pihole-http
    port: 80
    protocol: TCP
    targetPort: pihole-http
  - name: dns
    port: 53
    protocol: TCP
    targetPort: dns
  selector:
    k8s-app: pihole
  sessionAffinity: None
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/address-pool: lan-loadbalancer
    metallb.universe.tf/allow-shared-ip: lan-loadbalancer
  labels:
    k8s-app: pihole
  name: pihole-udp-100
  namespace: lan
spec:
  externalTrafficPolicy: Cluster
  loadBalancerIP: 192.168.1.100
  ports:
  - name: dns-udp
    port: 53
    protocol: UDP
    targetPort: dns-udp
  selector:
    k8s-app: pihole
  sessionAffinity: None
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/address-pool: lan-loadbalancer
    metallb.universe.tf/allow-shared-ip: lan-loadbalancer
  labels:
    k8s-app: pihole
  name: pihole-tcp-250
  namespace: lan
spec:
  externalTrafficPolicy: Cluster
  loadBalancerIP: 192.168.1.250
  ports:
  - name: pihole-http
    port: 80
    protocol: TCP
    targetPort: pihole-http
  - name: dns
    port: 53
    protocol: TCP
    targetPort: dns
  selector:
    k8s-app: pihole
  sessionAffinity: None
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/address-pool: lan-loadbalancer
    metallb.universe.tf/allow-shared-ip: lan-loadbalancer
  labels:
    k8s-app: pihole
  name: pihole-udp-250
  namespace: lan
spec:
  externalTrafficPolicy: Cluster
  loadBalancerIP: 192.168.1.250
  ports:
  - name: dns-udp
    port: 53
    protocol: UDP
    targetPort: dns-udp
  selector:
    k8s-app: pihole
  sessionAffinity: None
  type: LoadBalancer
