apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "9"
    description: LAN pihole
  creationTimestamp: null
  generation: 1
  labels:
    k8s-app: pihole
    app: pihole
    location: lan
  name: pihole
  selfLink: /apis/extensions/v1beta1/namespaces/lan/deployments/pihole
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s-app: pihole
      location: lan
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        description: LAN pihole
      creationTimestamp: null
      labels:
        k8s-app: pihole
        location: lan
      name: pihole
    spec:
      containers:
      - env:
        - name: TZ
          value: Berlin/Europe
#        - name: ServerIP
#          value: 192.168.1.100
        - name: WEBPASSWORD
          value: test123
#        volumeMounts:
#        - mountPath: /etc/pihole
#          name: k8s-cfg-pihole
#        - mountPath: /etc/dnsmasq.d
#          name: k8s-cfg-pihole
        image: pihole/pihole
        imagePullPolicy: Always
        name: pihole
#        ports:
#        - containerPort: 80
#          name: pihole-http
#          protocol: TCP
#        - containerPort: 53
#          name: dns
#          protocol: TCP
#        - containerPort: 53
#          name: dns-udp
#          protocol: UDP
#        - containerPort: 443
#          name: pihole-ssl
#          protocol: TCP
#        - containerPort: 67
#          name: client-udp
#          protocol: UDP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        securityContext:
          privileged: false
          procMount: Default
      dnsPolicy: ClusterFirst
      hostNetwork: true
      restartPolicy: Always
      nodeSelector:
        location: lan
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
#      volumes:
#      - name: k8s-cfg-pihole
#        hostPath:
#          path: /root/k8s-cfg/pihole
#          type: Directory
status: {}
