apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/address-pool: lan-loadbalancer
    metallb.universe.tf/allow-shared-ip: pihole-svc
  labels:
    app: pihole
  name: pihole-udp
  namespace: lan
spec:
  externalTrafficPolicy: Local
  loadBalancerIP: 192.168.1.100
  ports:
  - name: dns-udp
    port: 53
    protocol: UDP
    targetPort: dns-udp
#  - name: client-udp
#    port: 67
#    protocol: UDP
#    targetPort: client-udp
  selector:
    app: pihole
  sessionAffinity: None
  type: LoadBalancer
