apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/address-pool: lan-loadbalancer
    metallb.universe.tf/allow-shared-ip: pihole-svc
  labels:
    k8s-app: pihole
  name: pihole-tcp-250
  namespace: lan
spec:
  externalTrafficPolicy: Local
  loadBalancerIP: 192.168.1.250
  ports:
  - name: pihole-http
    port: 80
    protocol: TCP
    targetPort: pihole-http
#  - name: pihole-https
#    port: 443
#    protocol: TCP
#    targetPort: pihole-https
#  - name: dns
#    port: 53
#    protocol: TCP
#    targetPort: dns
  selector:
    k8s-app: pihole
  sessionAffinity: None
  type: LoadBalancer
