apiVersion: batch/v1
kind: Job
metadata:
  name: pihole
spec:
  template:
    spec:
      containers:
      - name: pihole
        image: pihole/pihole
        command: ["cmd",  "-Mbignum=bpi", "-wle", "print bpi(2000)"]
      restartPolicy: Never
  backoffLimit: 4
